### ISSUE TITLE
Handle dirty OAS - or not, if in "strict" mode

### ISSUE THREAD

**Issue by ErikWittern** [IBM/openapi-to-graphql#12]
OAS are inherently dirty - see https://github.ibm.com/apiharmony/oasgraph/issues/45. E.g., schema definitions can be incomplete or missing completely.

I propose that OASGraph generally attempts to degrade gracefully, i.e., continue to work partially. In some places, this is already the case. For example, when an operation does not have a (valid) return schema defined, OASGraph simply logs a warning. In other cases, OASGraph currently crashes. For example, when the items of an array lack a proper schema definition.

I propose OASGraph per default logs warnings, but continues to work (partially). However, I propose to also introduce a `strict` option, which, if set to `true`, will make OASGraph throw an error and exit.

**Comment by Alan-Cha** [comment]
Resolved with the [strict option](https://github.com/strongloop/oasgraph#options).
