### ISSUE TITLE
Property with ref in "definitions" resolved to use ref name instead of prop name

### ISSUE THREAD

**Issue by JennieJi** [IBM/openapi-to-graphql#183]
Actually I am not sure whether this supports v2 or v3 spec?

**Describe the bug**
OAS (:
```json
{
  ...
  "paths": {
    "/my_api": {
      "get": {
        "responses": {
          "200": {
            "schema": {  "$ref": "#/definitions/Response" }
          },
          "products": [ "application/json" ]
        }
      }
    },
    ...
  },
  "definitions": {
    "Response": {
      "type": "object",
      "properties": {
        "data": {
          "type": "object",
          "$ref": "#/definitions/Item"
        }
      }
    },
    "Item": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number"
        }
      }
    }
  }
}
```

Will be resolved to graphql:
```graphql
type Query {
  getMyQuery: Response
}
type Response {
  item: Item
}
type Item {
  id: Int
}
```

**To Reproduce**
1. createGraphQlSchema with above schema
2. check in GraphiQL document
or use cli to generate graphql file

**Expected behavior**
```graphql
type Query {
  getMyQuery: Response
}
type Response {
  data: Item
}
type Item {
  id: Int
}
```

**Screenshots**
-

**Additional context**
-

**Comment by JennieJi** [comment]
I might try to look into this by my own, but may I know whether this is expected behavior or bug?

**Comment by Alan-Cha** [comment]
@JennieJi Thank you for trying out our library! 

We are built for the v3 spec but we use the [swagger2openapi](https://www.npmjs.com/package/swagger2openapi) library to convert v2 specs into v3. For example, we take advantage of [link objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#linkObject), a unique aspect of the v3 spec, to created nested object types.

Yes, this seems to be a bug. Thank you so much for filling a PR!

**Comment by JennieJi** [comment]
Thanks @Alan-Cha for replying so fast. This lib perfectly fulfilled my requirement of experimenting on a layer over RESTful API.

**Comment by Alan-Cha** [comment]
Glad to hear that we fit your needs! It's always cool to hear from people using our tool!
