### ISSUE TITLE
Supporting GraphQLID

### ISSUE THREAD

**Issue by omarchehab98** [IBM/openapi-to-graphql#187]
>ID: The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache. The ID type is serialized in the same way as a String; however, defining it as an ID signifies that it is not intended to be human‐readable.
> https://graphql.org/learn/schema/#scalar-types

Support emitting `GraphQLID` (https://graphql.org/graphql-js/type/#graphqlid)

# Implementation Details

I peeped around the codebase, here are some ideas I got:

File `schema_builder.ts`, function `getScalarType`, add

```js
    case 'id':
      def.ot = GraphQLID // TODO: Update import {GraphQLID} from 'graphql'
      break
```

File `oas_3_tools.ts`, function `getSchemaType`, add something along the lines of:

```js
  // CASE: id
  if (schema.format === 'graphql-id') {
    return 'id'
  }
```

**Comment by Alan-Cha** [comment]
Ah! This is a great change! Thank you so much! Will take a look into it.
