### ISSUE TITLE
Broken link in README.md > Characterisitcs > Nested data

### ISSUE THREAD

**Issue by mathieucaroff** [IBM/openapi-to-graphql#198]
**Describe the bug**
`/README.md` contains a broken link to `https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#linksObject` instead of `https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md#link-Object`.

(They renamed the file from `3.0.md` to `3.0.0.md` and `linksObject` to `link-Object`.)

**To Reproduce**
1. Go to `https://github.com/IBM/openapi-to-graphql#characteristics`
2. Click on 'Links' in the sentence "Nested data Links defined in..."
3. See error: page 404

**Note**
It may not be the only broken link of the page

---

I'm hesitant regarding the good strategy to use to avoid broken link in the future. I guess the safest would be to link to a specific commit tree, though it doesn't result in a nice URL.

**Comment by Alan-Cha** [comment]
Thank you for pointing this out! This is very helpful!

I'm not sure what the best strategy is either. For the time being, I don't mind fixing them from time to time.
