### ISSUE TITLE
HTML Error response breaks server

### ISSUE THREAD

**Issue by prevuelta** [IBM/openapi-to-graphql#203]
When there is an HTML error response from an API endpoint the server throws an error when it tries to run `JSON.parse(body)` , can we add a check to see what content type the response is? I'm running into this problem when my api gateway sends a timeout error

**Comment by Alan-Cha** [comment]
Ah okay! This would be a good addition! Will take a look into it. Thanks for the tip! 😊

**Comment by ErikWittern** [comment]
So, the idea would be to return the unparsed response (whatever it would be) in an error from GraphQL?

@Alan-Cha Could we use error extensions for this?
