### ISSUE TITLE
Multiple object fields referencing the same component in OAS become one field with wrong key

### ISSUE THREAD

**Issue by prevuelta** [IBM/openapi-to-graphql#206]
eg.
```
 "thing1": {
   "$ref": "#/components/schemas/thingSchema"
 },
"thing2": {
   "$ref": "#/components/schemas/thingSchema"
 },
"thing3": {
   "$ref": "#/components/schemas/thingSchema"
},

```
becomes: 
```
thingSchema: thingSchema
```
should become:
```
thing1: thingSchema,
thing2: thingSchema,
thing3: thingSchema

```

The problem is in preprocessor.ts
https://github.com/IBM/openapi-to-graphql/blob/71b93a3bccfcc13c1c25ef0d65fad9905acc9944/packages/openapi-to-graphql/src/preprocessor.ts#L562-L597

**Comment by Alan-Cha** [comment]
Hmmm... this seems a bit odd to me. I thought we addressed this with PR #184 (see issue #183 for more information). I will have to take a closer look tomorrow morning.

**Comment by prevuelta** [comment]
I think I need to update my package version - sorry! looks like resolved already

**Comment by Alan-Cha** [comment]
@prevuelta No problem! In any case, thank you so much for filling these issues though! They are very helpful!
