### ISSUE TITLE
Sanitization vs sanitation

### ISSUE THREAD

**Issue by Alan-Cha** [IBM/openapi-to-graphql#21]
We need to be more careful with how we describe "API sanitization/sanitation". There are references to both across the project. I propose we use the term "sanitization/sanitize" because the technical term is "data sanitization".

**Comment by ErikWittern** [comment]
The `sanitize` function is currently a one-liner, and the name is misleading as the resulting string is NOT GraphQL compliant.

We should: move the one line from the current `sanitize` function into the current `beautify` function. Then, rename `beautify` (and its sister functions) into `sanitize`.
