### ISSUE TITLE
How to expose graphql oasgraph in Docker image?

### ISSUE THREAD

**Issue by federicogomeza** [IBM/openapi-to-graphql#212]
I am creating an application in loopback 4, using graphql.

The problem I have is that I can not expose graphql oasgraph in Docker image

I have two options:
1 - Create a new dockerfile to expose graphql.
2 - Use the same loopback dockerfile to expose port 3000 (Explorer API at http://127.0.0.1:3000/explorer), and 3001 for graphql (http://127.0.0.1:3001/graphql).

How can I configure my dockerfile, in order to expose the graphql server?

https://loopback.io/doc/en/lb4/exposing-graphql-apis.html

This is my dockerfile

FIRST OPTION
```
# Check out https://hub.docker.com/_/node to select a new base image
FROM hasura/graphql-engine

# Create app directory (with user `node`)
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

RUN npm i -g openapi-to-graphql-cli

RUN npx oasgraph http://localhost:3000/openapi.json/

# Bind to all network interfaces so that it can be mapped to the host OS
ENV HOST=0.0.0.0 PORT=3001

EXPOSE ${PORT}

CMD [ "npx", "oasgraph", "http://localhost:3000/openapi.json/" ]
```

SECOND OPTION:
```
# Check out https://hub.docker.com/_/node to select a new base image
##FROM node:10-slim
## node con oracle instant client
FROM collinestes/docker-node-oracle

# Set to a non-root built-in user `node`
USER node

# Create app directory (with user `node`)
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY --chown=node package*.json ./

RUN npm install
# Install openapi-to-graphql-cli 
RUN npm i openapi-to-graphql-cli


# Bundle app source code
COPY --chown=node . .

RUN npm run build

# RUN oasgraph 
RUN npx oasgraph http://localhost:3000/openapi.json/

# Bind to all network interfaces so that it can be mapped to the host OS
ENV HOST=0.0.0.0 PORT=3000

EXPOSE ${PORT}

CMD [ "node", "." ]
```

**Comment by ErikWittern** [comment]
@fga8 It seems that the LoopBack tutorial you link to is outdated. Specifically, every use of `oasgraph` should be replaced by `openapi-to-graphql`. To fix that, an issue with LoopBack should be filed.

Apart from that, looking at your Docker files, I notice a few things:

In the first option, I don't see how you start the LoopBack app, but then you are trying to run OpenAPI-to-GraphQL, pointing it to the OpenAPI exposed by the app.

In the second option, it is unclear to me where the application source code comes into play? It looks like you are copying a package.json into an empty repository, and only install dependencies, but not copy the application code itself.

**Comment by Alan-Cha** [comment]
@ErikWittern I filed a [pull request](https://github.com/strongloop/loopback-next/pull/3361) on LoopBack regarding the outdated names/commands.

**Comment by fga8** [comment]
@ErikWittern Thank you very much for responding, and I updated my code to openapi-to-graphql.

**Is there an example of a dockerfile with openapi-to-graphql?**

My loopback dockerfile works correctly. I still have to create my dockerfile of openapi-to-graphql

**Comment by Alan-Cha** [comment]
Unfortunately, we currently do not have any example Dockerfiles. With the changes that Erik suggested, were you able to make any improvements?

**Comment by dhmlau** [comment]
Cross posting from: https://github.com/strongloop/loopback-next/issues/3346#issuecomment-515555994
-----

@fga8, I might have a working Dockerfile for you:
```
# Check out https://hub.docker.com/_/node to select a new base image
FROM node:10-slim

# Set to a non-root built-in user `node`
USER node

# Create app directory (with user `node`)
RUN mkdir -p /home/node/app

WORKDIR /home/node/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY --chown=node package*.json ./

RUN npm install
RUN npm install openapi-to-graphql-cli

# Bundle app source code
COPY --chown=node . .

RUN npm run build

# Bind to all network interfaces so that it can be mapped to the host OS
ENV HOST=0.0.0.0 PORT=3000 PORT2=3001 .  <--- Change this line to add PORT2 here

EXPOSE ${PORT}
EXPOSE ${PORT2} <----- Add this line


CMD (npm start &) ; (sleep 5) ; (npx openapi-to-graphql http://0.0.0.0:3000/openapi.json -p 3001) <--- Change this line
```

I've indicated 3 places that you need to make changes if you're using the `Dockerfile` generated by the LoopBack cli.  Please note that I'm not a docker expert, so what I have above is something that works, you might be able to find a better solution. 

For the sake of posterity, let me mention a few challenges:
1. `oasgraph` has been deprecated and the new module is `openapi-to-graphql`
2. In order to make sure `openapi-to-graphql` is not using the same port as LB, I've used `-p` option to specify the port number. (Thanks @ErikWittern)
3. I find the `sleep` in the `CMD` is needed, otherwise `openapi-to-graphql` will get started before the openapi is ready from LB. 

Hope it helps!
