### ISSUE TITLE
My openapi.json used to work with the current oasgraph-cli but now it is completely broken.

### ISSUE THREAD

**Issue by haalcala** [IBM/openapi-to-graphql#219]
My openapi.json used to work with the current oasgraph-cli but now it is completely broken.

In command line:

`openapi-to-graphql-cli -p 4999 https://loopback4-sample-heroes.herokuapp.com/openapi.json`

In browser:

`http://localhost:4999/graphql`

**Comment by Alan-Cha** [comment]
Do you know the version of the CLI when it worked? 

Are you absolutely sure that the OAS has not changed? The OAS makes use of a `where` parameter that is of type object but contains no properties. These kinds of schemas are very difficult for us to deal with as there's no way to express this in GraphQL... I don't think we have support for these kinds of cases which makes me believe that the OAS has been changed. I'm assuming that you are using LoopBack based off the URL. Is it possible that something changed? An update to Loopback, perhaps?

**Comment by haalcala** [comment]
Hi, thanks for your reply.

Are you referring to 'changed' as in the data returned by the URL is different if I used 'openapi-to-graphql-cli' or the 'oasgraph'(cli), given the same URL?

Btw, if I didn't mention specifically, that URL still works with a normal 'oasgraph'(cli).

**Comment by Alan-Cha** [comment]
@haalcala I meant if the content of the remote file has changed since the last time you tried it with the OASGraph CLI and it worked. 

It still works with the OASGraph CLI? Do you know what version you’re running? Just run `oasgraph -V`

**Comment by haalcala** [comment]
Thanks for your quick reply again.

The version says: 0.4.3
