### ISSUE TITLE
How can I set JSON graphql type?

### ISSUE THREAD

**Issue by josepmorey** [IBM/openapi-to-graphql#226]
Hi! Thanks for the library, it's pretty cool!

We have a problem when we want to set JSON graphql type. In openapi not exist JSON type so when we put JSON oas validator fails. How can I set it?

Thanks

**Comment by Alan-Cha** [comment]
Hi! Thanks for trying out our library! If you want to use the GraphQL JSON type, all you need to do is set the schema to an object and do *not* set any properties, like the following schema:

```
{
  “type”: “object”
}
```

The JSON scalar type, in some ways, goes against the GraphQL design philosophy of strong typing. We added this feature for better compatibility with existing OASs, not so much to be used deliberately. Just something to keep in mind! Let us know if you have any other questions.

**Comment by josepmorey** [comment]
Perfect! We updated the package and with latest version works fine, thanks! good job!
