### ISSUE TITLE
Auto parse fields from snake_case to camelCase on schema fields

### ISSUE THREAD

**Issue by josepmorey** [IBM/openapi-to-graphql#227]
Hi! We have a problem about auto parsing snake_case to camelCase of schema fields. How we can disable this? We have fields of model for example "target_id" and don't want to parse to "targetId".

The same problem occurs when the reponse is JSON graphql type:
`{"DATA1": "something"}`

parsed to: 

`{"dATA1": "something"}`

Thanks

**Comment by Alan-Cha** [comment]
Hi @josepmorey! We currently don't have an option to disable this, although we could potentially add one. The reason why we enforce camelCase is to follow GraphQL conventions (see #98).

**Comment by josepmorey** [comment]
I understand, but we need that fields be the same in openapi than graphql. Might be the convencions could be able with strict mode or some param...

**Comment by Alan-Cha** [comment]
@josepmorey Ok! Just something to keep in mind is that even if we do provide an option, we cannot guarantee that the GraphQL fields will have the same names as those in the OAS. The names will still need to go through sanitization, which will ensure that the names use the [character pattern](https://graphql.github.io/graphql-spec/draft/#sec-Names) allowed in the spec. 

I think for the examples you gave me, nothing should change.

**Comment by pktippa** [comment]
Not sure this is similar here, but facing an issue where when i try to mutate, the camelcase key is getting converted to snake case..

**Comment by Alan-Cha** [comment]
@pktippa This sounds like a very bizarre problem. You are saying that you intend the key to be camelCase but OtG converts it into a snake_case? Can you also describe where this key exists? Is it part of the OAS?

**Comment by pktippa** [comment]
@Alan-Cha yes the key exists in OAS as camelCase expecting for mutation from graphql, but when i get the mutation payload in [Loopback 3](https://github.com/strongloop/loopback) [custom remote method](https://loopback.io/doc/en/lb3/Remote-methods.html), i am getting the key in snake case.

**Comment by Alan-Cha** [comment]
@pktippa This is very strange. Is it possible for you to file a separate issue and provide an OAS (or a snippet of it) so we can isolate the problem and try to fix it?

**Comment by pktippa** [comment]
@Alan-Cha Sure will do.

**Comment by phillip-hogan** [comment]
Hi @Alan-Cha, has there been any decision as to whether you might be adding this as an option (disabling parsing of snake_case to camelCase)? Currently looking at options/approaches as we have a similar issue to Josep.

**Comment by Alan-Cha** [comment]
@phillip-hogan I think we should add an option as suggested. It should only remove [illegal characters](https://graphql.github.io/graphql-spec/draft/#sec-Names) and maintain as much of the original name as possible.

We are about to make a major release that will include significant changes to how we sanitize names. I think we should begin to work on the option after the release.

**Comment by ibudden** [comment]
@Alan-Cha (cc @phillip-hogan) is this something we can help with? We have a certain time pressure on this here so would be very happy to contribute if that is useful.

**Comment by Alan-Cha** [comment]
@ibudden Actually you could! That would be very helpful! I don't see it as being very difficult. 

I would recommend taking a look at PR #287 and creating a fork off of my [branch](https://github.com/Alan-Cha/oasgraph/tree/anyOf_oneOf4). I will try to get the PR in on Friday and I think it should be possible to get this feature in early next week. 

We will need to define a new option [here](https://github.com/Alan-Cha/oasgraph/blob/4b0d59853588fd1a1fa736321d2f8459d3917938/packages/openapi-to-graphql/src/types/options.ts#L29) and [here](https://github.com/Alan-Cha/oasgraph/blob/4b0d59853588fd1a1fa736321d2f8459d3917938/packages/openapi-to-graphql/src/types/options.ts#L183). Perhaps we can call it `simpleFieldNames` and it should be a boolean. Then we will need to process the option [here](https://github.com/Alan-Cha/oasgraph/blob/4b0d59853588fd1a1fa736321d2f8459d3917938/packages/openapi-to-graphql/src/index.ts#L76). 

The field name is assigned [here](https://github.com/Alan-Cha/oasgraph/blob/4b0d59853588fd1a1fa736321d2f8459d3917938/packages/openapi-to-graphql/src/schema_builder.ts#L598) so I think we just need to manipulate the logic [here](https://github.com/Alan-Cha/oasgraph/blob/4b0d59853588fd1a1fa736321d2f8459d3917938/packages/openapi-to-graphql/src/schema_builder.ts#L589). I think we should create a default behavior of [`sanitize` function](https://github.com/Alan-Cha/oasgraph/blob/4b0d59853588fd1a1fa736321d2f8459d3917938/packages/openapi-to-graphql/src/oas_3_tools.ts#L1038) that just removes illegal characters. We can just check for the option here and then use the default sanitization.

In addition, we also need to make a similar change [here](https://github.com/Alan-Cha/oasgraph/blob/4b0d59853588fd1a1fa736321d2f8459d3917938/packages/openapi-to-graphql/src/preprocessor.ts#L475), where we add additional fields from link objects. 

Let me know if you have any questions and if you would like to contribute!

**Comment by ibudden** [comment]
Brilliant notes thank you - we'll get on with that.

**Comment by ibudden** [comment]
@Alan-Cha - thanks again for the notes. 
I've sent over a PR - so do feed back - happy to make changes if needed.

**Comment by Alan-Cha** [comment]
@ibudden This is fantastic! I can take over the PR from here. This is great work!

In terms of releases, I think we're on track for getting something out next week.

**Comment by Alan-Cha** [comment]
@ibudden Thank you so much for your work. It really helped me to make PR #291. Feel free to review it if you have the time.

**Comment by Alan-Cha** [comment]
In v2.0.0, we now have the `simpleNames` option which will only remove illegal characters! 🎉
