### ISSUE TITLE
Schema reference as argument to "allOf" type

### ISSUE THREAD

**Issue by dominikks** [IBM/openapi-to-graphql#237]
**Describe the bug**
When a schema reference is used as argument to the `allOf` property, OpenAPI-to-GraphQL terminates with an error saying that the schema reference can not be resolved. I discovered this working with the GitHub v3 API. A minimal demo is provided [here](https://github.com/dominikks/openapi-to-graphql-bug-demo). The OpenAPI document causing the error is [demo.json](https://github.com/dominikks/openapi-to-graphql-bug-demo/blob/master/demo.json).

The OpenAPI document contains the following schema type:
```
"repo": {
  "properties": {
    "parent": {
      "allOf": [
        { "$ref": "#/components/schemas/repo" }
      ]
    }
  },
  "type": "object"
}
```
Running `openapi-to-graphql` on this doc results in the following output:
```
OpenAPI-to-GraphQL creation event error:  Cannot process schema '{"$ref":"#/components/schemas/repo"}'. Cannot identify type of schema.
```
Modifying the schema type as follows resolves the error:
```
"repo": {
  "properties": {
    "parent": {
      "$ref": "#/components/schemas/repo"      
    }
  },
  "type": "object"
}
```

**To Reproduce**
1. Clone the [demo repository](https://github.com/dominikks/openapi-to-graphql-bug-demo).
`git clone https://github.com/dominikks/openapi-to-graphql-bug-demo.git`
2. `cd openapi-to-graphql-bug-demo`
3. `npm install`
4. `npm run demo`

**Expected behavior**
OpenAPI-to-GraphQL should complete without error.

**Additional context**
I believe the problem is cased by the combination of a schema reference in an `allOf` type as removing the `allOf` part resolves the problem.

**Comment by Alan-Cha** [comment]
@dominikks Thank you so much for this beautifully filed issue! And the additional minimal demo repo is so helpful as well! 

Yeah, the problem is that we're not dereferencing the reference in `allOf`. I believe #215 should fix it. We have yet to release it however. 

I will try to replicate this error with the WIP version. We also plan on releasing a new version today so keep an eye on the fix!

**Comment by dominikks** [comment]
Allright, thanks for the quick reply! Great to hear that the issue is already being addressed. I will try replicating the issue with the new version as soon as it is released. 🙂

**Comment by Alan-Cha** [comment]
Hmmm, okay, it seems that the PR is not sufficient to fix this error. It seems to be a different sort of problem. It's a little bit convoluted to explain but I think some refactoring will get things in order. Will let you know how it goes!

**Comment by Alan-Cha** [comment]
Fixed! The bug does not appear when you install OtG v1.6.0!
