### ISSUE TITLE
Unable to run it on a clean loopback app

### ISSUE THREAD

**Issue by danysz** [IBM/openapi-to-graphql#241]
Create a loopback app `lb4 app test`
Enter the directory `cd test`
Install the package : `npm i --save openapi-to-graphql-cli`
Run `npm start`
Check that server is running on port 300 .
Try to run `npx openapi-to-graphql http://localhost:3000/openapi.json` (from documentation)

**Expected behavior**
Have the GraphQL on port 3001

** Error **
Error: listen EADDRINUSE: address already in use :::3000

**Comment by Alan-Cha** [comment]
The documentation needs to be updated. Can you point me to it? 

Run `npx openapi-to-graphql http://localhost:3000/openapi.json -p 3001` instead. Let me know if this works for you!

**Comment by danysz** [comment]
I found the "-p" parameter so I solved the problem for myself but either to change the default or to update the documentation as you said. Here is the link with the documents :
https://loopback.io/doc/en/lb4/exposing-graphql-apis.html

**Comment by Alan-Cha** [comment]
Glad to hear you were able to fix it! I will try to fix the documentation tomorrow. Sorry for the trouble!

**Comment by Alan-Cha** [comment]
This has been taken care of with the following PR: https://github.ibm.com/IBMCode/Code-Tutorials/pull/2133
