### ISSUE TITLE
feature request: handle inconsistent/incompatible schema

### ISSUE THREAD

**Issue by tirumaraiselvan** [IBM/openapi-to-graphql#248]
Since there are lot of constructs in OpenAPI that do not map well to GraphQL like `anyOf`, `allOf` etc, openapi-to-graphql fails to launch on such schemas.

Instead of failing to launch, is it possible to "drop" parts of the schema which cannot be resolved and throw warnings that these parts are dropped. This can be enabled through a flag like `--drop-incompatible-schema` or something.

This will allow users with schemas like Stripe etc to get access to many APIs in GraphQL which might be enough for their use-case.

**Comment by Alan-Cha** [comment]
@tirumaraiselvan Thanks for the suggestion! I think you make some fair points. 

I can see two possibilities right now. As we are translating each operation, if we encounter a schema that we cannot process, we can 1) simply skip the operation or 2) default to [GraphQL JSON type](https://github.com/taion/graphql-type-json) and treat the schema and the field like a black box. The first option should be a lot easier the implement than the second option. The second option involves trying to coordinate between the schema and the resolver builders. 

What are your thoughts?

***

I'm sorry I still haven't finished `anyOf`, `oneOf`, and `not` support yet. I know it's been an open issue for quite a while now. I've just been so busy with other work.

**Comment by tirumaraiselvan** [comment]
I was thinking of the first. I am not sure I understand the full implications of second.

**Comment by dazgirl** [comment]
any progress? I got same issue, UnhandledPromiseRejectionWarning with "oneOf"

**Comment by Alan-Cha** [comment]
@kargalskaya I'm making slow progress on my [branch](https://github.com/Alan-Cha/oasgraph/tree/anyOf_oneOf2) (it's also messy because I'm trying out different things) but still a work in progress. 

Would love if people wanted to help out on the effort as there are a lot of people who are interested in the fix but it's still quite a complex problem so I wouldn't be sure how to organize it.

**Comment by Alan-Cha** [comment]
@tirumaraiselvan @kargalskaya We finally have a fix for this problem! Update to v2.0.0 and take a look at this [post](https://github.com/IBM/openapi-to-graphql/issues/197#issuecomment-579459330)!
