### ISSUE TITLE
Error: Cannot process schema $ref Cannot identify type of schema.

### ISSUE THREAD

**Issue by sbrin** [IBM/openapi-to-graphql#258]
I'm trying to use createGraphQlSchema as described in documentation but getting this error related to local references:

```
(node:252) UnhandledPromiseRejectionWarning: Error: Cannot process schema '{"$ref":"#/components/schemas/Id_2"}'. Cannot identify type of schema.
    at createDataDef (D:\Projects\graphql\node_modules\openapi-to-graphql\lib\preprocessor.js:436:19)
...
```

How can i fix this issue? Why it cannot process local references?

Here is parts of my JSON spec where i use references:

```
// openapi.json
...
    "order_id" : {
              "$ref" : "#/components/schemas/Id_2"
            },
...
"components" : {
    "schemas" : {
...
        "Id_2" : {
            "type" : "string",
            "description" : "Unique order identifier.",
            "example" : "bcc669fa-ef1f-429b-8dea-1bf5ac78f457"
          },
...
    }
}
```

**Comment by Alan-Cha** [comment]
@sbrin This is very strange. It should definitely be able to handle this case... I will take a look...

**Comment by Alan-Cha** [comment]
I could not replicate this error at all. Is it possible to share the entire OAS?

**Comment by sbrin** [comment]
I published a simple project to display my issue: https://github.com/sbrin/createGraphQlSchema_issue

**Comment by Alan-Cha** [comment]
@sbrin I am confused about this simple project. This simple project does not produce the error you mentioned before. The error I get comes from the OAS validator which suggests a more fundamental problem with the OAS. The first problem is that the OAS relies on non-standard reference syntax (e.g. "Deck API#/components/schemas/inline_response_200"). Upon fixing these references, there still seems to be missing references in the OAS (e.g. "#/components/schemas/Payment_Status"). However, putting all these aside, I don't see any "order_id" or "Id_2" components in the schema. If you can clarify all of this, that would be very helpful.

**Comment by Alan-Cha** [comment]
After correcting the references and removing the missing ones, I was able to generate a working GraphQL interface.

**Comment by sbrin** [comment]
Thank you for your support.
It was just a short part of my OAS. You're right: after fixing my mistakes it works fine. But i still have schemaValidate exception when i'm trying to process full version of OAS (which is strange because it was generated from working YAML spec using openapi-generator).

I guess we can close this issue. Thank you for your support.
