### ISSUE TITLE
Error: DUPLICATE_FIELD_NAME

### ISSUE THREAD

**Issue by simax** [IBM/openapi-to-graphql#261]
**Describe the bug**
UnhandledPromiseRejectionWarning: Error: DUPLICATE_FIELD_NAME - Multiple operations have the same name 'categories'. GraphQL field names must be unique so only one can be added to the Query object. Operation 'GET /api/v1/categories' will be ignored.

**To Reproduce**
Use the swagger.txt file with the app.js below

**Expected behavior**
To run without error

I'm resurrecting a project from approx 10 months ago and have updated from NPM package `OASGraph 0.13.0` to `openapi-to-graphql version 1.6.1`.  Understandably many things have changed in the past 10 months or so and it's not surprising that when I try to run the project I'm seeing some errors. 

This swagger.txt file worked in the past but now it's complaining about duplicates. I thought OASGraph used to work based on `operationId`. Has that changed?

My app.js code looks like this:

```
const express = require("express");
const graphqlHTTP = require("express-graphql");
const { createGraphQlSchema } = require("openapi-to-graphql");
const bodyParser = require("body-parser");

async function startServer() {
  // use OASGraph to create a GraphQL schema:
  const oas = require("./swagger.txt");
  const { schema } = await createGraphQlSchema(oas, {
    strict: true,
    tokenJSONpath: "$.user.token"
  });

  function getToken() {
    return "my bearer token" // not shown here.
  }

  const app = express();
  app.use(bodyParser.json());

  app.use(
    "/",
    graphqlHTTP({
      context: { user: { token: getToken() } },
      schema: schema,
      graphiql: true
    })
  );

  app.listen(3000, () => {
    console.log("GraphQL => http://localhost:3000/graphiql");
  });
}

// kick things off:
startServer();
```

[This is the swagger file I'm using. ](https://github.com/IBM/openapi-to-graphql/files/3756328/swagger.txt)

Also, in the `Authorization` section of the `readme` [there is a link to an example](https://github.ibm.com/apiharmony/oasgraph-oauth-github-example)  which doesn't appear to be reachanble without some credentials.

Hope you can help.

**Comment by simax** [comment]
OK, ignore this, looks like it was because I had **strict** mode enabled:

```
const { schema } = await createGraphQlSchema(oas, {
  strict: true,
  ...
});
```

**Comment by Alan-Cha** [comment]
Hmmm, interesting... I actually get a different error:

```
OpenAPI-to-GraphQL creation event error:  DUPLICATE_FIELD_NAME - Multiple operations have the same name 'plan'. GraphQL field names must be unique so only one can be added to the Query object. Operation 'GET /api/v1/settings/plans/{id}' will be ignored.
```

I am also running OtG v1.6.1... What version of Node are you running? 

***

This error makes sense though, `GET /api/v1/settings/plans/current` and `GET /api/v1/settings/plans/{id}` both return a `Plan` object, so they both try to compete for the same field name `plan`. OtG tries to fall back on the `operationId` but the `operationId` of `GET /api/v1/settings/plans/{id}` is also `Plan` so it breaks. 

***

Just to clarify, OtG does not create (query) field names using the `operationId`, at least **not** by default. To configure OtG to do so, you have to enable the `operationIdFieldNames` option. I believe this behavior is the same as it was back in 0.13.0 and before. 

(Query) field names are generated from the return type of the field. In non-strict mode, it will default to the `operationId` if there is a name collision (and throw an error if that is still the case). 

***

Yes, the authorization example is not publicly available. We need to move it and it has been very long overdue. Thanks for bringing it to our attention again. Related: #52

**Comment by simax** [comment]
`operationIdFieldNames` did the trick. I knew there was a setting somewhere - but it's been a while :) All working now. Thanks for your help.
