### ISSUE TITLE
LoopBack 4 relations

### ISSUE THREAD

**Issue by TomerSalton** [IBM/openapi-to-graphql#272]
**Describe the bug**
When setting a relation between objects, the GraphQL Documentation Explorer is empty, and in the result pane, there is an error: "Object type Fields2Input must define one or more fields".

**To Reproduce**
1. Create a new loopback 4 application.
2. Generate a simple 'Customer' entity with default CRUD.
3. Generate a simple 'Order' entity with default CRUD.
4. Associate the Order to the Customer by a hasMany relation.
5. Associate the Customer to the Order by a belongsTo relation.
6. Run loopback, and then run the tool with http://localhost:3000/openapi.json as input.

Please advise,
Tomer.

**Comment by Alan-Cha** [comment]
@TomerSalton Thanks for filing this issue! I think I have an idea of what's going on. However, is it possible for you to check in your LoopBack application as a GitHub repo for easier debugging? And if that is not possible, is it possible to check in the OAS from your app as a GitHub Gist? Also what version of OtG are you on? Are you on the latest version v1.6.2?

I think the problem may be related to #219 as well as [this](https://github.com/strongloop/loopback4-example-family-tree/issues/3). Basically, GraphQL is strongly-typed whereas OAS is not. I believe somewhere in the schema, there is an operation that has a [requestBody](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#requestBodyObject) that does not have a descriptive object type schema, meaning it does not contain a `properties` field. I thought I resolved this problem but perhaps there are still issues.

**Comment by TomerSalton** [comment]
Hi @Alan-Cha ,

Thanks for your quick reply 🙂

1. I am using latest version (1.6.2.).
2. here's a [link to the LoopBack application repository](https://github.com/TomerSalton/oas-to-graphql-issue) I created, hope it helps.

Please let me know if you need anything.

**Comment by Alan-Cha** [comment]
@TomerSalton I fixed the problem and made a PR #275! The problem was that we made a check for an undefined object but did not consider an empty object.
