### ISSUE TITLE
header parameters incorrectly added as operation input parameters

### ISSUE THREAD

**Issue by mikestaub** [IBM/openapi-to-graphql#278]
If a parameter is expected to be passed in the request header and not the body, it should not be added as an input variable. 

Here is an example of a broken schema:

```
swagger: "2.0"
info:
  version: "1.0.0"
  title: Test API

host: localhost:1339
basePath: /

schemes:
  - http
  - https

consumes:
  - application/json
produces:
  - application/json

x-servers:
  - url: //api.test.com
    description: Default server

paths:
  /v1/files:
    post:
      parameters:
        - $ref: "#/parameters/headerparam"
      summary: Create a file
      operationId: postFile
      description: Creates a new file
      responses:
        "201":
          description: Success
          schema:
            $ref: "#/definitions/File"

parameters:
  headerparam:
    name: headerparam
    type: string
    in: header
    required: true
    pattern: "[a-zA-Z0-9-_]+"
    minLength: 1
    maxLength: 128

definitions:
  Type:
    enum:
      - TEST_ENUM
    type: string

  File:
    type: object
    properties:
      cadType:
        $ref: "#/definitions/Type"

```

**Comment by Alan-Cha** [comment]
@mikestaub Once again, thank you so much for filling this issue and even providing a sample OAS to test with! I'm actually a little bit surprised that we've encountered so many issues with OtG but I'm glad we are able to debug them now with your help. I will take a look at this later today and I'm happy to report I've made progress on some of the other issues you've filed. Currently waiting for a coworker to accept my PR.

**Comment by mikestaub** [comment]
Thanks for being so responsive to my issues, I really appreciate it. This library is providing a lot of value, when I get some extra cycles I will gladly contribute.

**Comment by Alan-Cha** [comment]
@mikestaub Thanks for the PR! Actually, I would like to ask for some clarification. We do intend to add headers as arguments and they should be passed as a request header to the API. 

I tried to simulate a GraphQL query using your example and these were the headers that were sent. 

```
mutation {
  postFile(headerparam: "hello") {
    cadType
  }
}
```

```
{
  "headerparam":"hello",
  "content-type":"application/json",
  "accept":"application/json"
}
```

***

If the user does not want to create header arguments, he/she can use the [`headers` option](https://github.com/IBM/openapi-to-graphql/tree/master/packages/openapi-to-graphql#options) and OtG will avoid adding them to the GraphQL interface. That logic can be found [here](https://github.com/IBM/openapi-to-graphql/blob/44385871286982574b96bc60a9e505ef2a2b7570/packages/openapi-to-graphql/src/schema_builder.ts#L874).

I do see that there are improvements needed in these areas though. I think we should have more explicit documentation of this hidden feature and we currently do not ignore headers if they are provided through `requestOptions`. I will try to take care of this. 

***

Besides those things, I am a little bit confused by your suggestion. It seems from the PR, you simply do not want OtG to generate arguments for headers at all. Could you clarify that?

**Comment by mikestaub** [comment]
I'm sorry I should have read the docs more closely, I can just use the headers option like you suggested, you can close the issue and PR.

My opinion is that we should treat headers and body parameters differently. If an API is expecting headers to be passed, those vars should not be a part of the graphQL operation variables, as they will be parsed from the headers not the body in the actual service.

**Comment by Alan-Cha** [comment]
@mikestaub Awesome! I will also try to improve the documentation. 

I think your opinion is also valid. The reason why we have this feature is more for completeness's sake, however if the user provides headers using a different path, then we will avoid creating unnecessary arguments.

**Comment by Alan-Cha** [comment]
Amended documentation and logic for handling headers in #283

**Comment by mikestaub** [comment]
I am setting the headers option to remove it from the operation arguments, but I want to override the actual header at runtime ( from the http request ). When I do this using `graphql-middleware` I still see the hardcoded header being sent to the underlying service. Is this expected?

**Comment by Alan-Cha** [comment]
@mikestaub Yes, I believe this is expected. The header is hardcoded when you set it using the `headers` option.

If you would like to dynamically change the headers at runtime, then I would recommend you to take a look at issue #234 and PR #270.
