### ISSUE TITLE
LinkResolver doesn't receive requestOptions

### ISSUE THREAD

**Issue by sotaokuhama** [IBM/openapi-to-graphql#292]
`requestOptions` works fine with resolvers except for linkResolvers. Is there any workaround for that?

**Comment by Alan-Cha** [comment]
@sotaokuhama Yes, this is a bug and thank you so much for filing a PR! I think the one thing that is missing is adding a test to make sure we don't let this slip by a second time (which I will do). Also, I'm very glad to hear that our links feature is being used!

**Comment by Alan-Cha** [comment]
I added tests in #294

**Comment by sotaokuhama** [comment]
@Alan-Cha Thanks for adding tests so quick! Is there anything else I could help so that it can get merged?

**Comment by Alan-Cha** [comment]
@sotaokuhama Hopefully, this will be merged in tomorrow. There's a possibility that we still need to move the release to next week though...

**Comment by Alan-Cha** [comment]
@sotaokuhama Published 2.0.0! This should be resolved! Thanks for the help! 🥂
