### ISSUE TITLE
Links and $response.body "null" values

### ISSUE THREAD

**Issue by ryanpab** [IBM/openapi-to-graphql#298]
Hello.
I am in need of advice on how to handle "links" getting their values from "$response.body" attributes and having a null value.
Our API returns null values which trigger these linked requests but putting "null" in the path parameters.
What's the best approach to resolve this?
Any help will be much appreciated.

**Comment by Alan-Cha** [comment]
Ah sorry, I am currently cleaning out our issues and I realized that I did not respond to this issue. I will close it for now but if you still need help, just let me know. I hope you were able to resolve this issue on your own.
