### ISSUE TITLE
Comments in generated GQL code

### ISSUE THREAD

**Issue by TWry** [IBM/openapi-to-graphql#302]
I found many comments in the generated code which seem to use six double quotes. Unfortunately this code cannot be parsed by e.g. graphql-dotnet. Is there some way to tell openapi-to-graphql to use hashmarks for comments?

**Comment by TWry** [comment]
Just for the record, here's what the GraphQL specification says concerning comments: http://spec.graphql.org/June2018/#sec-Comments

**Comment by Alan-Cha** [comment]
@TWry Sorry for the late reply! Are you saying when you print out the schema, you get comments (to be more accurate, descriptions) with six double quotes? If so, then I believe this is out of our control. The specs describes descriptions [here](http://spec.graphql.org/June2018/#sec-Descriptions). It sounds to me that this a feature that is lacking in graphql-dotnet. We don't have any control over how these descriptions are represented. Let me know if this is helpful or not!

**Comment by TWry** [comment]
@Alan-Cha I am sorry, I guess you are right. I did not know descriptions and they seem to be lacking in graphql-dotnet. Thanks for your help!
