### ISSUE TITLE
Unable to parse loopback-example with openapi-to-graphql library

### ISSUE THREAD

**Issue by vtapadia** [IBM/openapi-to-graphql#337]
**Describe the bug**
Unable to parse simple ping interface API from loopback.

**To Reproduce**
Run the loopback example project with just the ping interface.
(Sample project https://github.com/vtapadia/loopback-example)
Create another project that uses the openapi-to-graphql lib
(Example: https://github.com/vtapadia/graphql-from-openapi)
Follow the steps and replace set the `oas` variable as follows
`const oas = ["http://localhost:3000/openapi.json"]`
Start this application with simple node command
`node index.js`
Server fail to start with following error
(node:16960) UnhandledPromiseRejectionWarning: Invalid specification provided

**Expected behavior**
Server should be up but it is failing with the following reason.

**Comment by Alan-Cha** [comment]
@vtapadia Thank you so much for filling this issue. We definitely want to support LoopBack-made APIs. 

This actually seems to be an error with the [OAS validator](https://www.npmjs.com/package/oas-validator) that we are using. As a result, there isn't too much we can do from our side as the library is out of our control.

I will still investigate to see what exactly is the issue.

A relate issue is #334 which discusses replacing our validator.

**Comment by vtapadia** [comment]
@Alan-Cha Thanks for the remark. But this does not make sense.

I tried the same API with the CLI and it worked. I would assume that the CLI is just a wrapper on top of the actual library. But maybe I am wrong.

Here is the output from the CLI.
```
$ openapi-to-graphql http://localhost:3001/openapi.json
{
  "warnings": [],
  "numOps": 1,
  "numOpsQuery": 1,
  "numOpsMutation": 0,
  "numOpsSubscription": 0,
  "numQueriesCreated": 1,
  "numMutationsCreated": 0,
  "numSubscriptionsCreated": 0
}
GraphQL accessible at: http://localhost:3000/graphql
```

Could you help me understand the discrepancy?

**Comment by vtapadia** [comment]
Nevermind, I looked at the openapi-to-graphql-cli project and realized that the service needs a JSON parsed object. After doing that, the issue is resolved.
