### ISSUE TITLE
Question :Support For Generating SDL for some of the API Operations and Not For All

### ISSUE THREAD

**Issue by ganesh-p** [IBM/openapi-to-graphql#340]
### Question :Support For Generating SDL for some of the API Operations and Not For All.

We are using openapi-to-graphql library for our GraphQL Development to generate SDL from API Schema. we have a requirement like, have to generate typedefs only for some of the API operations and not for all. How do we go about doing it? Should we modify the API Schema or is there any support available in this library to generate only for selected operations .

Thank you.

**Comment by Alan-Cha** [comment]
Sorry for the late reply, I totally missed this issue. I believe this is related to #281. 

Currently, I don't think anyone is actively working on an option that can do this. However, you should be able to control which operations OtG will process by simply editing the OAS. Let me know if this solution will work for you.

**Comment by Alan-Cha** [comment]
I will close this issue for now. If you have any concerns, please consider voicing them in the other issue #281

**Comment by ganesh-p** [comment]
Thank you Alan for reply.


Regards,

Ganesh
