### ISSUE TITLE
PathItemObject description should be optional

### ISSUE THREAD

**Issue by FallingSnow** [IBM/openapi-to-graphql#345]
Shouldn't https://github.com/IBM/openapi-to-graphql/blob/17a5b2dd9f5b9c90703216fa8c18bb82c4f09372/packages/openapi-to-graphql/src/types/oas3.ts#L168 be optional.

According to the spec
> An optional, string description, intended to apply to all operations in this path. CommonMark syntax MAY be used for rich text representation.
https://swagger.io/specification/#path-item-object

**Comment by Alan-Cha** [comment]
Similar to the other issue (#346), I was able to fix this one in 50aeb89d709f8ef97de3b213430f13c93e164875.
