### ISSUE TITLE
SchemaObject should allow boolean for additionalProperties

### ISSUE THREAD

**Issue by FallingSnow** [IBM/openapi-to-graphql#346]
Shouldn't `additionalProperties` be allowed to be boolean.
https://github.com/IBM/openapi-to-graphql/blob/17a5b2dd9f5b9c90703216fa8c18bb82c4f09372/packages/openapi-to-graphql/src/types/oas3.ts#L29

Specification states:
> additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. Consistent with JSON Schema, additionalProperties defaults to true.
https://swagger.io/specification/#schema-object

**Comment by Alan-Cha** [comment]
@FallingSnow Thank you so much for reporting this! I was able to fix this issue in 50aeb89d709f8ef97de3b213430f13c93e164875. I think for the future, we should consider using a module that can provide the typings for us (see #348).
