### ISSUE TITLE
Can't convert OpenAPI 3 to GraphQL Spec

### ISSUE THREAD

**Issue by sebastianfelipe** [IBM/openapi-to-graphql#352]
I have an API with its OpenAPI 3.0.1 spec already validated. But when I try to use the openapi-to-graphql, it doesn't work. It is an advanced API, so if this works with this API, I think a lot of users will be very happy.

https://api.xompass.com/explorer/swagger.json

The error is weird, because is said that the title that is named "cloud-api" should be boolean instead of string, you will see it when you run it.

Thanks!

**Comment by Alan-Cha** [comment]
Sorry for the late reply. I will take a look sometime soon. From the way you describe it, this sounds like a problem with our OAS validator. There is an issue filed for removing this dependency and outsourcing the validation step to the user #334
