### ISSUE TITLE
Fetch Reference Error When Saving To File

### ISSUE THREAD

**Issue by bryanbalmer** [IBM/openapi-to-graphql#438]
**Describe the bug**
Reference error for 'fetch' when trying to save a generated file with the CLI.

**To Reproduce**
1. Run CLI with 'https://petstore.swagger.io/v2/swagger.json' endpoint and --save flag set

**Expected behavior**
Expected file to generate without error

**Screenshots**
![image](https://user-images.githubusercontent.com/5375228/148317004-b789ecbc-8f98-428d-86e4-5aadeea23614.png)

**Comment by Alan-Cha** [comment]
This has been fixed with version v2.6.1 thanks to your PR! Thanks for reporting the issue and submitting a fix!
