### ISSUE TITLE
Upgrade to Graphql 16

### ISSUE THREAD

**Issue by StarpTech** [IBM/openapi-to-graphql#458]
Hi, this library throws warnings when using Graphql 16.

```
├─┬ @types/express-graphql
│ └─┬ express-graphql
│   └── ✕ unmet peer graphql@"^14.7.0 || ^15.3.0": found 16.3.0
└─┬ openapi-to-graphql
  ├── ✕ unmet peer graphql@"^14.0.0 || ^15.0.0": found 16.3.0
  └─┬ graphql-subscriptions
    └── ✕ unmet peer graphql@"^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0": found 16.3.0

```
We can fix it by:

- Upgrading `graphql-subscriptions` to `2.0.0`
-  Replace `express-graphql` with https://github.com/contra/graphql-helix because the module seems unmaintained.

Would you accept a PR?

**Comment by Alan-Cha** [comment]
@StarpTech Thanks for reporting this. Yes, if you are willing to provide a PR, I can review and accept it.

**Comment by mhassan1** [comment]
@StarpTech I took a first pass at a PR: https://github.com/IBM/openapi-to-graphql/pull/471
