### ISSUE TITLE
Add custom headers option to CLI

### ISSUE THREAD

**Issue by ErikWittern** [IBM/openapi-to-graphql#89]
When used as a library, OASGraph allows to define custom headers to be sent in every HTTP request to the wrapped REST(-like) API, as described in the [options]{https://github.com/strongloop/oasgraph/tree/master/packages/oasgraph#options}.

However, this feature is not available when using OASGraph via CLI. A new `headers` option should allow users to define custom headers to send, for example, authentication tokens. This was also brought up in issue #88.

**Comment by gtamas** [comment]
Any news on this? This would be a very useful feature, especially since many REST APIs require headers to be sent with every request for authentication.

**Comment by Alan-Cha** [comment]
@gtamas the problem we’re facing is we don’t know how to expose the option. It is easy to create flags for binary options but difficult to do so for more complex options such as this one or `customResolvers`. 

Should it point to a file? What should the file contain and in what format? These are all questions that are up in the air.

Another thing to consider is that, while the whole topic is a bit grey, we intended the CLI to be a simple wrapper for the library. We wanted people to use the CLI to get a taste for the library, but not use it for production per say. While this view can change, I say this just to point out that in the past, we did not set out to ensure that the CLI had the same feature set as the library. I think we should start rethinking this strategy as we start getting more users and have a better idea of how people want to use OtG.

**Comment by gtamas** [comment]
@Alan-Cha 
OK I see, thanks for the explanation.

As for the headers flag, I think it should be just a simple mechanism, like a  CLI flag called --header which allows you to define a HTTP header in the usual way (headerName: value). It should be possible to repeat this flag, so one can define as many headers as he / she wishes.

Another option is to use only a single --headers flag whose value is a JSON string: {"headerName": "value", "header2Name": "value2" }

Regarding viewers, I don't think I can use them. Authentication in my case requires sending certain headers with each request. I think currently there is no built-in viewer for this, right?

**Comment by Alan-Cha** [comment]
@gtamas The first method you proposed, is this a fairly common interface design? Forgive me for not being more knowledgeable. I think it's definitely nicer than providing a JSON object, whether it be directly in the command line or through a file. 

***

I'm not sure what your authentication needs are but I think our viewers can at least handle simple cases such as using basic authentication or API keys.

**Comment by gtamas** [comment]
@Alan-Cha 
I think it's common, yes. For example this is how cURL works and several command-line parser libs support this as well (e.g: yargs, commander, optimist etc ). Also specifying the header's value in this form is quite common.

By the way, you could add support defining query string parameters the same way. Like --qs foo:1 --qs bar: 2

Viewers: ok thx. Unfortunately that's not gonna work in my case. I need to send custom things like sessionToken, username etc. Anyway,I already solved this. I used OtG as a lib instead of CLI.

**Comment by Alan-Cha** [comment]
@gtamas Thank you so much for the insight! I will look into adding this feature then. Glad to hear that you were still able to solve your authentication problem!
