### ISSUE TITLE
Support GraphQL conventions

### ISSUE THREAD

**Issue by Alan-Cha** [IBM/openapi-to-graphql#98]
Conventions are important because they allow developers to create projects that are consistent and easily understandable by other developers. 

What are some of these conventions and how can we make sure OASGraph supports them?

**Comment by ErikWittern** [comment]
Just for completeness, some are:

* PascalCased type names (see #99)
* camelCased field names (OASGraph already does this)
* CAPITALIZED enum values
* `Input` postfix for Input Object Types (OASGraph already does this)

**Comment by Alan-Cha** [comment]
I see, so the next step would be to convert enum values to all-caps. Should this be an option?

**Comment by ErikWittern** [comment]
W.r.t. enum values: If we change a value, let's say from `hour` to `HOUR`, we need to make sure that at runtime, we translate back and forth. I think we should try to stick to GraphQL conventions as much as possible, so I propose to default to making enum values all caps generally. I don't see why there needs to be an option to disable this behavior - in the end, the GraphQL interface has its own UX, which is going to be different from the REST(-like) API.

**Comment by JennieJi** [comment]
Would you also transform all the REST API response fields to make sure resolvers work as expected (I met a bug that my API responded in lowercase and underscore separated, but Graphql transformed all these to camelcase)?

**Comment by Alan-Cha** [comment]
We currently have support for GraphQL conventions with this [commit](https://github.com/IBM/openapi-to-graphql/commit/bfdc2f1ff9288561474eb7574c7dc211c847c364) and the release of v2.0.0
